### PR TITLE
Add timeouts for web, client ecs

### PR DESCRIPTION
**Pull request by AlexKlim**

### CODE REVIEW

**Comment by itallmakesense** [comment]
- What's the reason of the change?
- Does aws provider version supports that change?

**Comment by AlexKlim** [comment]
@itallmakesense we have a timeout during the deployment of ECS for Client API. It looks like by default it is "10m", but we need more. 

I'd like to keep it as a separate version (tag) as the old AWS provider doesn't support this option. We should have a version (`~> 4.36`)

**Comment by itallmakesense** [comment]
> @itallmakesense we have a timeout during the deployment of ECS for Client API. It looks like by default it is "10m", but we need more.
> 
> I'd like to keep it as a separate version (tag) as the old AWS provider doesn't support this option. We should have a version (`~> 4.36`)

I'm afraid it won't help, because "steady state" check is unchangable and take 40 attempts of 15 seconds (40* 15 = 600 = 10 min): https://docs.aws.amazon.com/cli/latest/reference/ecs/wait/services-stable.html
If you need to exclude fails, you should set `wait_for_steady_state = false`.
If you still need to keep that, you can try to move wait to a separate (rerunable) step (instead of reruning the whole deployment pipeline): https://github.com/craft-machine/supply-chain/blob/main/.circleci/config.yml#L148

**Comment by AlexKlim** [comment]
@itallmakesense  actually it helps. on Friday I did it for QA and right now I am checking it for stage and production.

**Comment by itallmakesense** [comment]
> @itallmakesense actually it helps. on Friday I did it for QA and right now I am checking it for stage and production.

that's interesting... can you share the pipeline result? Is it really lasted > 10 min?

**Comment by adys** [comment]
> > @itallmakesense we have a timeout during the deployment of ECS for Client API. It looks like by default it is "10m", but we need more.
> > I'd like to keep it as a separate version (tag) as the old AWS provider doesn't support this option. We should have a version (`~> 4.36`)
> 
> I'm afraid it won't help, because "steady state" check is unchangable and take 40 attempts of 15 seconds (40* 15 = 600 = 10 min): https://docs.aws.amazon.com/cli/latest/reference/ecs/wait/services-stable.html If you need to exclude fails, you should set `wait_for_steady_state = false`. If you still need to keep that, you can try to move wait to a separate (rerunable) step (instead of reruning the whole deployment pipeline): https://github.com/craft-machine/supply-chain/blob/main/.circleci/config.yml#L148

@itallmakesense that's a great point. You are completely right. I didn't realise it.

@AlexKlim I agree with @itallmakesense and we should set wait_for_steady_state = false. We need to move wait to a separate (rerunable) step as I did for supply-chain -> https://github.com/craft-machine/supply-chain/blob/main/.circleci/config.yml#L148

**Comment by AlexKlim** [comment]
discussed in the Slack and decided to open a new one.

**Pull request closed without merging**
